server:
  port: 8081
spring:
  application:
    name: service-a

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  circuitbreaker:
    instances:
      serviceBCallCircuitBreaker:
        slidingWindowSize: 2
        minimumNumberOfCalls: 1
        failureRateThreshold: 50
        waitDurationInOpenState: 5s